using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
expected = "/home/snakagaw/drm_parity_integration_567fec06_001/src/DRM.jl"
realpath(pathof(DRM)) == realpath(expected) || error("wrong DRM checkout")
println("RUNTIME julia=", VERSION, " threads=", Threads.nthreads(), " BLAS=", BLAS.get_num_threads(), " DRM=", pathof(DRM)); flush(stdout)
println("START_FILE test_bootstrap.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_bootstrap.jl")
println("COMPLETE_FILE test_bootstrap.jl"); flush(stdout)
println("START_FILE test_bootstrap_marginal.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_bootstrap_marginal.jl")
println("COMPLETE_FILE test_bootstrap_marginal.jl"); flush(stdout)
println("START_FILE test_gaussian_spatial.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_gaussian_spatial.jl")
println("COMPLETE_FILE test_gaussian_spatial.jl"); flush(stdout)
println("START_FILE test_predict.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_predict.jl")
println("COMPLETE_FILE test_predict.jl"); flush(stdout)
println("BOOTSTRAP_NEXT_COMPLETE"); flush(stdout)
