using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
expected = "/home/snakagaw/drm_parity_integration_567fec06_001/src/DRM.jl"
realpath(pathof(DRM)) == realpath(expected) || error("wrong DRM checkout")
println("RUNTIME julia=", VERSION, " threads=", Threads.nthreads(), " BLAS=", BLAS.get_num_threads(), " DRM=", pathof(DRM)); flush(stdout)
println("START_FILE test_student.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_student.jl")
println("COMPLETE_FILE test_student.jl"); flush(stdout)
println("START_FILE test_skewnormal.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_skewnormal.jl")
println("COMPLETE_FILE test_skewnormal.jl"); flush(stdout)
println("START_FILE test_poisson.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_poisson.jl")
println("COMPLETE_FILE test_poisson.jl"); flush(stdout)
println("START_FILE test_nbinom2.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_nbinom2.jl")
println("COMPLETE_FILE test_nbinom2.jl"); flush(stdout)
println("START_FILE test_nb2_dispersion_seed.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_nb2_dispersion_seed.jl")
println("COMPLETE_FILE test_nb2_dispersion_seed.jl"); flush(stdout)
println("START_FILE test_beta.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_beta.jl")
println("COMPLETE_FILE test_beta.jl"); flush(stdout)
println("START_FILE test_gamma.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_gamma.jl")
println("COMPLETE_FILE test_gamma.jl"); flush(stdout)
println("START_FILE test_eta_clamp_parity.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_eta_clamp_parity.jl")
println("COMPLETE_FILE test_eta_clamp_parity.jl"); flush(stdout)
println("START_FILE test_zi.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_zi.jl")
println("COMPLETE_FILE test_zi.jl"); flush(stdout)
println("START_FILE test_lognormal.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_lognormal.jl")
println("COMPLETE_FILE test_lognormal.jl"); flush(stdout)
println("START_FILE test_hurdle.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_hurdle.jl")
println("COMPLETE_FILE test_hurdle.jl"); flush(stdout)
println("START_FILE test_truncated_nb.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_truncated_nb.jl")
println("COMPLETE_FILE test_truncated_nb.jl"); flush(stdout)
println("START_FILE test_betabinomial.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_betabinomial.jl")
println("COMPLETE_FILE test_betabinomial.jl"); flush(stdout)
println("START_FILE test_zeroonebeta.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_zeroonebeta.jl")
println("COMPLETE_FILE test_zeroonebeta.jl"); flush(stdout)
println("START_FILE test_tweedie.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_tweedie.jl")
println("COMPLETE_FILE test_tweedie.jl"); flush(stdout)
println("START_FILE test_cumulative.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_integration_567fec06_001/test/test_cumulative.jl")
println("COMPLETE_FILE test_cumulative.jl"); flush(stdout)
println("FAMILY_CORE_COMPLETE"); flush(stdout)
