using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
@assert realpath(pathof(DRM))==joinpath(pwd(),"src","DRM.jl")
println("RUNTIME julia=",VERSION," threads=",Threads.nthreads()," blas=",BLAS.get_num_threads()," source=",pathof(DRM))
println("TEST_FILE test_joint_missing_two_predictor.jl"); @time include("test/test_joint_missing_two_predictor.jl")
println("TEST_FILE test_joint_missing_two_frontend.jl"); @time include("test/test_joint_missing_two_frontend.jl")
println("TEST_FILE test_joint_missing_two_bridge.jl"); @time include("test/test_joint_missing_two_bridge.jl")
println("TEST_FILE test_joint_missing_finite.jl"); @time include("test/test_joint_missing_finite.jl")
println("TEST_FILE test_joint_missing_finite_frontend.jl"); @time include("test/test_joint_missing_finite_frontend.jl")
println("TEST_FILE test_joint_missing_finite_bridge.jl"); @time include("test/test_joint_missing_finite_bridge.jl")
println("TEST_FILE test_phylo_polytomy.jl"); @time include("test/test_phylo_polytomy.jl")
println("TEST_FILE test_phylo_labels.jl"); @time include("test/test_phylo_labels.jl")
println("TEST_FILE test_phylo_polytomy_kernels.jl"); @time include("test/test_phylo_polytomy_kernels.jl")
println("TEST_FILE test_lss_tip_identity.jl"); @time include("test/test_lss_tip_identity.jl")
println("TEST_FILE test_lss_bootstrap_contract.jl"); @time include("test/test_lss_bootstrap_contract.jl")
println("TEST_FILE test_bootstrap_thread_flags.jl"); @time include("test/test_bootstrap_thread_flags.jl")
println("TEST_FILE test_bridge_profile_status.jl"); @time include("test/test_bridge_profile_status.jl")
println("TEST_FILE test_bridge_formula_labels.jl"); @time include("test/test_bridge_formula_labels.jl")
println("TOTORO_INTEGRATION_PASS")
