using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
@assert realpath(pathof(DRM)) == realpath("/home/snakagaw/drm_parity_blas_c0675b16_001/src/DRM.jl")
println("RUNTIME julia=",VERSION," JuliaThreads=",Threads.nthreads()," BLAS=",BLAS.get_num_threads()," source=",pathof(DRM)); flush(stdout)
println("START_FILE test_locscale_structured.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_structured.jl")
println("COMPLETE_FILE test_locscale_structured.jl"); flush(stdout)
println("START_FILE test_sigma_axis_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_sigma_axis_re.jl")
println("COMPLETE_FILE test_sigma_axis_re.jl"); flush(stdout)
println("START_FILE test_nonconst_sigma_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_nonconst_sigma_re.jl")
println("COMPLETE_FILE test_nonconst_sigma_re.jl"); flush(stdout)
println("LOCSCALE_SUFFIX_COMPLETE"); flush(stdout)
