using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
@assert realpath(pathof(DRM)) == realpath("/home/snakagaw/drm_parity_blas_c0675b16_001/src/DRM.jl")
println("RUNTIME julia=",VERSION," JuliaThreads=",Threads.nthreads()," BLAS=",BLAS.get_num_threads()," source=",pathof(DRM)); flush(stdout)
println("START_FILE test_poisson_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_poisson_re.jl")
println("COMPLETE_FILE test_poisson_re.jl"); flush(stdout)
println("START_FILE test_poisson_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_poisson_slope_re.jl")
println("COMPLETE_FILE test_poisson_slope_re.jl"); flush(stdout)
println("START_FILE test_poisson_crossed_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_poisson_crossed_laplace.jl")
println("COMPLETE_FILE test_poisson_crossed_laplace.jl"); flush(stdout)
println("START_FILE test_poisson_phylo_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_poisson_phylo_laplace.jl")
println("COMPLETE_FILE test_poisson_phylo_laplace.jl"); flush(stdout)
println("START_FILE test_relmat_counts.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_relmat_counts.jl")
println("COMPLETE_FILE test_relmat_counts.jl"); flush(stdout)
println("START_FILE test_relmat_counts_nb2.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_relmat_counts_nb2.jl")
println("COMPLETE_FILE test_relmat_counts_nb2.jl"); flush(stdout)
println("START_FILE test_relmat_counts_beta.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_relmat_counts_beta.jl")
println("COMPLETE_FILE test_relmat_counts_beta.jl"); flush(stdout)
println("START_FILE test_spatial_coord_poisson.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_spatial_coord_poisson.jl")
println("COMPLETE_FILE test_spatial_coord_poisson.jl"); flush(stdout)
println("START_FILE test_nb2_phylo_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_nb2_phylo_laplace.jl")
println("COMPLETE_FILE test_nb2_phylo_laplace.jl"); flush(stdout)
println("START_FILE test_gamma_beta_phylo_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_gamma_beta_phylo_laplace.jl")
println("COMPLETE_FILE test_gamma_beta_phylo_laplace.jl"); flush(stdout)
println("START_FILE test_binomial_phylo_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_binomial_phylo_laplace.jl")
println("COMPLETE_FILE test_binomial_phylo_laplace.jl"); flush(stdout)
println("START_FILE test_betabinomial_phylo_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_betabinomial_phylo_laplace.jl")
println("COMPLETE_FILE test_betabinomial_phylo_laplace.jl"); flush(stdout)
println("START_FILE test_crossed_laplace_generic.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_crossed_laplace_generic.jl")
println("COMPLETE_FILE test_crossed_laplace_generic.jl"); flush(stdout)
println("START_FILE test_betabinomial_crossed_laplace.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_betabinomial_crossed_laplace.jl")
println("COMPLETE_FILE test_betabinomial_crossed_laplace.jl"); flush(stdout)
println("START_FILE test_crossed_selected_inverse.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_crossed_selected_inverse.jl")
println("COMPLETE_FILE test_crossed_selected_inverse.jl"); flush(stdout)
println("STRUCTURED_CORE_COMPLETE"); flush(stdout)
