using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
@assert realpath(pathof(DRM)) == realpath("/home/snakagaw/drm_parity_blas_c0675b16_001/src/DRM.jl")
println("RUNTIME julia=",VERSION," JuliaThreads=",Threads.nthreads()," BLAS=",BLAS.get_num_threads()); flush(stdout)
println("START_FILE test_nbinom2_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_nbinom2_slope_re.jl")
println("COMPLETE_FILE test_nbinom2_slope_re.jl"); flush(stdout)
println("START_FILE test_beta_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_beta_slope_re.jl")
println("COMPLETE_FILE test_beta_slope_re.jl"); flush(stdout)
println("START_FILE test_gamma_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_gamma_slope_re.jl")
println("COMPLETE_FILE test_gamma_slope_re.jl"); flush(stdout)
println("START_FILE test_nbinom2_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_nbinom2_re.jl")
println("COMPLETE_FILE test_nbinom2_re.jl"); flush(stdout)
println("START_FILE test_beta_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_beta_re.jl")
println("COMPLETE_FILE test_beta_re.jl"); flush(stdout)
println("START_FILE test_gamma_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_gamma_re.jl")
println("COMPLETE_FILE test_gamma_re.jl"); flush(stdout)
println("START_FILE test_student_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_student_re.jl")
println("COMPLETE_FILE test_student_re.jl"); flush(stdout)
println("START_FILE test_student_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_student_slope_re.jl")
println("COMPLETE_FILE test_student_slope_re.jl"); flush(stdout)
println("START_FILE test_lognormal_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_lognormal_re.jl")
println("COMPLETE_FILE test_lognormal_re.jl"); flush(stdout)
println("START_FILE test_lognormal_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_lognormal_slope_re.jl")
println("COMPLETE_FILE test_lognormal_slope_re.jl"); flush(stdout)
println("START_FILE test_betabinomial_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_betabinomial_re.jl")
println("COMPLETE_FILE test_betabinomial_re.jl"); flush(stdout)
println("START_FILE test_betabinomial_slope_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_betabinomial_slope_re.jl")
println("COMPLETE_FILE test_betabinomial_slope_re.jl"); flush(stdout)
println("START_FILE test_binomial.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_binomial.jl")
println("COMPLETE_FILE test_binomial.jl"); flush(stdout)
println("START_FILE test_binomial_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_binomial_re.jl")
println("COMPLETE_FILE test_binomial_re.jl"); flush(stdout)
println("START_FILE test_summary.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_summary.jl")
println("COMPLETE_FILE test_summary.jl"); flush(stdout)
println("FAMILY_RE_COMPLETE"); flush(stdout)
