using DRM, Test, LinearAlgebra
BLAS.set_num_threads(1)
@assert realpath(pathof(DRM)) == realpath("/home/snakagaw/drm_parity_blas_c0675b16_001/src/DRM.jl")
println("RUNTIME julia=",VERSION," JuliaThreads=",Threads.nthreads()," BLAS=",BLAS.get_num_threads()," source=",pathof(DRM)); flush(stdout)
println("START_FILE test_locscale_kernels.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_kernels.jl")
println("COMPLETE_FILE test_locscale_kernels.jl"); flush(stdout)
println("START_FILE test_locscale_inner.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_inner.jl")
println("COMPLETE_FILE test_locscale_inner.jl"); flush(stdout)
println("START_FILE test_locscale_marginal.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_marginal.jl")
println("COMPLETE_FILE test_locscale_marginal.jl"); flush(stdout)
println("START_FILE test_locscale_fit.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_fit.jl")
println("COMPLETE_FILE test_locscale_fit.jl"); flush(stdout)
println("START_FILE test_locscale_grad.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_grad.jl")
println("COMPLETE_FILE test_locscale_grad.jl"); flush(stdout)
println("START_FILE test_locscale_infer.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_infer.jl")
println("COMPLETE_FILE test_locscale_infer.jl"); flush(stdout)
println("START_FILE test_locscale_profile.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_profile.jl")
println("COMPLETE_FILE test_locscale_profile.jl"); flush(stdout)
println("START_FILE test_optimizer_robustness.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_optimizer_robustness.jl")
println("COMPLETE_FILE test_optimizer_robustness.jl"); flush(stdout)
println("START_FILE test_locscale_gamma_e2e.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_gamma_e2e.jl")
println("COMPLETE_FILE test_locscale_gamma_e2e.jl"); flush(stdout)
println("START_FILE test_locscale_phylo_e2e.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_phylo_e2e.jl")
println("COMPLETE_FILE test_locscale_phylo_e2e.jl"); flush(stdout)
println("START_FILE test_locscale_frontend.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_frontend.jl")
println("COMPLETE_FILE test_locscale_frontend.jl"); flush(stdout)
println("START_FILE test_locscale_structured.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_locscale_structured.jl")
println("COMPLETE_FILE test_locscale_structured.jl"); flush(stdout)
println("START_FILE test_sigma_axis_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_sigma_axis_re.jl")
println("COMPLETE_FILE test_sigma_axis_re.jl"); flush(stdout)
println("START_FILE test_nonconst_sigma_re.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_nonconst_sigma_re.jl")
println("COMPLETE_FILE test_nonconst_sigma_re.jl"); flush(stdout)
println("LOCSCALE_CORE_COMPLETE"); flush(stdout)
