using DRM, Test, LinearAlgebra
BLAS.set_num_threads(4)
@assert realpath(pathof(DRM)) == realpath("/home/snakagaw/drm_parity_blas_c0675b16_001/src/DRM.jl")
println("RUNTIME julia=",VERSION," JuliaThreads=",Threads.nthreads()," BLAS=",BLAS.get_num_threads()," source=",pathof(DRM)); flush(stdout)
println("START_FILE test_inference_blas_pinning.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_inference_blas_pinning.jl")
println("COMPLETE_FILE test_inference_blas_pinning.jl"); flush(stdout)
println("START_FILE test_bootstrap_thread_flags.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_bootstrap_thread_flags.jl")
println("COMPLETE_FILE test_bootstrap_thread_flags.jl"); flush(stdout)
println("START_FILE test_profile_ci.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_profile_ci.jl")
println("COMPLETE_FILE test_profile_ci.jl"); flush(stdout)
println("START_FILE test_bootstrap.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_bootstrap.jl")
println("COMPLETE_FILE test_bootstrap.jl"); flush(stdout)
println("START_FILE test_lss_bootstrap_contract.jl"); flush(stdout)
include("/home/snakagaw/drm_parity_blas_c0675b16_001/test/test_lss_bootstrap_contract.jl")
println("COMPLETE_FILE test_lss_bootstrap_contract.jl"); flush(stdout)
@test BLAS.get_num_threads() == 4
println("PROFILE_BOOTSTRAP_REGRESSION_COMPLETE BLAS=",BLAS.get_num_threads()); flush(stdout)
